INSERT INTO students (name,profile_pic) VALUES ('Debjyoti Roy', '/1.jpeg');
INSERT INTO students (name,profile_pic) VALUES ('Vasant Govind Patil','/2.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Kaustav Saha','/3.jpg' );
INSERT INTO students (name,profile_pic) VALUES ('Debobrata', '/4.jpg' );
INSERT INTO students (name,profile_pic) VALUES ('Anurag Mark Topno', '/5.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Tarun Minz','/6.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Praveen Rao Rokkam','/7.jpeg');
INSERT INTO students (name,profile_pic) VALUES ('Arindam Sharma', '/8.jpeg');
INSERT INTO students (name,profile_pic) VALUES ('Kaustubh Tripathi','/9.jpeg');
INSERT INTO students (name,profile_pic) VALUES ('Nakul Gupta','/10.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Gaurav Kumar','/11.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Abhiram Kasin','/12.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Biplab Sinha','/13.jpeg');
INSERT INTO students (name,profile_pic) VALUES ('M Jagan Mohan	','/14.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Asit Parij','/15.jpeg');
INSERT INTO students (name,profile_pic) VALUES ('Shenoy Naresh Keshav','/16.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Amit Kumar Suthar','/17.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Rahul Jaimini	','/18.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Rohit Rajgarhia','/19.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Akshit Sharma	','/20.jpeg');
INSERT INTO students (name,profile_pic) VALUES ('Divya Kumar Kala','/21.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Sri Harshad','/22.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Micky Mrinal Minz','/23.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Nishant Mundu	','/24.jpg');
INSERT INTO students (name,profile_pic) VALUES ('Vinu Rajashekhar','25.jpeg');
INSERT INTO quotes( quote) VALUES('Sky is our limit');
INSERT INTO quotes( quote) VALUES('Dream big');
INSERT INTO projects(teacher_ic, name, category, description) VALUES ('Mr Gray', 'Animal','Science', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos distinctio voluptas odit corporis dolore, beatae minima labore. Ea modi minus quos, pariatur sapiente, adipisci, enim voluptates at dicta a sunt?');
INSERT INTO projects(teacher_ic, name, category, description) VALUES ('Ms Wee', 'Flower','Science', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos distinctio voluptas odit corporis dolore, beatae minima labore. Ea modi minus quos, pariatur sapiente, adipisci, enim voluptates at dicta a sunt?');
INSERT INTO projects(teacher_ic, name, category, description) VALUES ('Ms Choo', 'Digital Art','Art', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos distinctio voluptas odit corporis dolore, beatae minima labore. Ea modi minus quos, pariatur sapiente, adipisci, enim voluptates at dicta a sunt?');
INSERT INTO projects(teacher_ic, name, category, description) VALUES ('Mr Jason', 'The Dark Age','Humanity', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos distinctio voluptas odit corporis dolore, beatae minima labore. Ea modi minus quos, pariatur sapiente, adipisci, enim voluptates at dicta a sunt?');
INSERT INTO projects(teacher_ic, name, category, description) VALUES ('Ms Helen', 'Rain forest','Humanity', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos distinctio voluptas odit corporis dolore, beatae minima labore. Ea modi minus quos, pariatur sapiente, adipisci, enim voluptates at dicta a sunt?');
INSERT INTO projects(teacher_ic, name, category, description) VALUES ('Md Cheong', '3D Printing','Art', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos distinctio voluptas odit corporis dolore, beatae minima labore. Ea modi minus quos, pariatur sapiente, adipisci, enim voluptates at dicta a sunt?');
INSERT INTO student_project(student_id, project_id) VALUES (1,1);
INSERT INTO student_project(student_id, project_id) VALUES (2,3);
INSERT INTO student_project(student_id, project_id) VALUES (3,3);
INSERT INTO student_project(student_id, project_id) VALUES (4,3);
INSERT INTO student_project(student_id, project_id) VALUES (5,3);
INSERT INTO student_project(student_id, project_id) VALUES (6,2);
INSERT INTO student_project(student_id, project_id) VALUES (7,2);
INSERT INTO student_project(student_id, project_id) VALUES (8,2);
INSERT INTO student_project(student_id, project_id) VALUES (9,4);
INSERT INTO student_project(student_id, project_id) VALUES (10,4);
INSERT INTO student_project(student_id, project_id) VALUES (11,4);
INSERT INTO student_project(student_id, project_id) VALUES (12,3);
INSERT INTO student_project(student_id, project_id) VALUES (13,5);
INSERT INTO student_project(student_id, project_id) VALUES (14,5);
INSERT INTO student_project(student_id, project_id) VALUES (15,5);
INSERT INTO student_project(student_id, project_id) VALUES (16,6);
INSERT INTO student_project(student_id, project_id) VALUES (17,6);
INSERT INTO student_project(student_id, project_id) VALUES (18,6);
INSERT INTO student_project(student_id, project_id) VALUES (19,1);
INSERT INTO student_project(student_id, project_id) VALUES (20,1);